require 'facturae_print/xml_objectifier'
require 'facturae_print/invoice'
require 'facturae_print/renderers/html_renderer_helpers'
require 'facturae_print/renderers/html_renderer'
require 'facturae_print/core_ext/string'